name: flutter_google_place_darkzy
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice
version: 1.0.0
homepage: https://github.com/DarkzyRB
repository: https://github.com/DarkzyRB/Flutter-Google-Place-Darkzy

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.4.5
#  google_maps_webservice: ^0.0.20-nullsafety.5
#  google_maps_webservice_ex: ^0.0.1+2
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.4.0
  rxdart: ^0.28.0
  rxdart_ext: ^0.3.0
  listenable_stream: ^2.0.1
  collection: ^1.19.1
  flutter_bloc_pattern: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/google_black.png
    - lib/assets/google_white.png
